config/routes.rb
Rails.application.routes.draw do
  resources :statics

  resources :courses

  mount Ckeditor::Engine => '/ckeditor'
  resources :departments

  resources :news

  resources :projects

  resources :events

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'api/v1/registrations' }
  resources :users
  get '/approve/:id' ,to: 'projects#approve', as: :approve
  get '/approval/' ,to: 'projects#approval', as: :approval
  get '/apply/:id' ,to: 'projects#apply', as: :apply
  post '/save_static' ,to: 'statics#save', as: :save_static
  get 'tags/:tag', to: 'projects#index', as: :tag

  namespace :api do
  namespace :v1 do
    devise_scope :user do
      # post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end
end


end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :user
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:name, :description, :date)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= simple_form_for(@news) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, :as => :ckeditor  %>
    <%= f.input :date %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<style>

  table { 
  border: solid;
  border-radius: 5px;

  /*border-style: solid,black,rounded;*/
  color: #333;
  font-family: Helvetica, Arial, sans-serif; 
  border-collapse: 
  collapse; border-spacing: 0; 
  }

  td, th { 
  border: 1px solid transparent; /* No more visible border */
  height: 30px; 
  transition: all 0.3s;  /* Simple transition for hover effect */
  }

  th {
  background: #D11919;  /* Darken header a bit */
  font-weight: bold;
  font-size: 18px;
  }

  td {
  background: #FAFAFA;
  text-align: center;
  }
  
  thead {
    text-align: center;
  }

  /* Cells in even rows (2,4,6...) are one color */ 
  tr:nth-child(even) td { background: #F1F1F1; }   

  /* Cells in odd rows (1,3,5...) are another (excludes header cells)  */ 
  tr:nth-child(odd) td { background: #FEFEFE; }  

  tr td:hover { background: #666; color: yellow; } /* Hover cell effect! */

  .myButton {
  -moz-box-shadow: 3px 4px 0px 0px #8a2a21;
  -webkit-box-shadow: 3px 4px 0px 0px #8a2a21;
  box-shadow: 3px 4px 0px 0px #8a2a21;
  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #c62d1f), color-stop(1, #f24437));
  background:-moz-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:-webkit-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:-o-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:-ms-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:linear-gradient(to bottom, #c62d1f 5%, #f24437 100%);
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#c62d1f', endColorstr='#f24437',GradientType=0);
  background-color:#c62d1f;
  -moz-border-radius:18px;
  -webkit-border-radius:18px;
  border-radius:18px;
  border:1px solid #d02718;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:arial;
  font-size:17px;
  padding:7px 55px;
  text-decoration:none;
  text-shadow:0px 1px 0px #810e05;
}
.myButton:hover {
  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #f24437), color-stop(1, #c62d1f));
  background:-moz-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:-webkit-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:-o-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:-ms-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:linear-gradient(to bottom, #f24437 5%, #c62d1f 100%);
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f24437', endColorstr='#c62d1f',GradientType=0);
  background-color:#f24437;
}
.myButton:active {
  position:relative;
  top:1px;
}

#event_date {
  
    width: 140px;
    height: 140px;
    background-color: #3366FF;
    box-shadow: 10px 10px 5px #888888;

}

#event_date:hover{
outline: 5px solid black;
}

#date {

  font: 30px Tahoma, Helvetica, Arial, Sans-Serif;
  text-align: center;
  color: #222;
  text-shadow: 0px 2px 3px #555;

}
</style>




<p id="notice"><%= notice %></p>

<h1>Listing News</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.name %></td>
        <td><%= news.description %></td>
        <td><%= news.date %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } if news.user == current_user%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @news.date %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>