config/routes.rb
Rails.application.routes.draw do
  resources :statics

  resources :courses

  mount Ckeditor::Engine => '/ckeditor'
  resources :departments

  resources :news

  resources :projects

  resources :events

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'api/v1/registrations' }
  resources :users
  get '/approve/:id' ,to: 'projects#approve', as: :approve
  get '/approval/' ,to: 'projects#approval', as: :approval
  get '/apply/:id' ,to: 'projects#apply', as: :apply
  post '/save_static' ,to: 'statics#save', as: :save_static
  get 'tags/:tag', to: 'projects#index', as: :tag

  namespace :api do
  namespace :v1 do
    devise_scope :user do
      # post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end
end


end

app/models/project.rb
class Project < ActiveRecord::Base
  	enum status: [:completed, :pending, :in_progress]

	acts_as_taggable
	# Proffessor
	belongs_to :mentor, class_name: 'User'
	# Student Teams
	has_and_belongs_to_many :members, class_name: 'User'
	accepts_nested_attributes_for :members, :reject_if => :check_member, :allow_destroy => true

	protected

    def check_member(member_attr)
    	puts member_attr.to_s + '*'*100
	    if _member = User.find(member_attr['name'])
	    	self.members << _member
	    	return true
	   	end
	    return false
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :approve, :apply]

  # GET /projects
  # GET /projects.json
  def index
    if params[:tag]
       @projects = Project.tagged_with(params[:tag])
    else
       @projects = Project.all
    end
  end

  def approval
    if current_user.nil?
      redirect_to root_path
      return
    end
    @projects = Project.where(:mentor => current_user)
    render 'index'
  end

  def approve
    @project.status = 'completed'
    @project.save
    redirect_to :back, notice: 'Project was successfully Approved.'
  end

  def apply
    @project.status = 'pending'
    @project.save
    redirect_to :back, notice: 'Project was successfully Approved.'
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    # Temp
    @students = User.all
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @students = User.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.status = :in_progress
    puts @project.members

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    puts @project.members
    @students = User.all

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :status, :domain, :tag_list, :mentor, :members, :mentor_id, members_attributes: [:name, :id ,:_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, :as => :ckeditor  %>
    <%# f.input :status %>
    <%= f.input :domain %>
    <%= f.input :tag_list %>
    <%= f.association :mentor %>
    <%= f.simple_fields_for :members do |member| %>
      <%= render 'member_fields', :f => member %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add member', f, :members %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_member_fields.html.erb
<div class="nested-fields">
  <%= f.error_notification %>
  <%= f.input :name, :collection => @students,:label_method => :name,:value_method => :id,:label => "Member" ,:include_blank => false %>
  <%# f.input :description %>
  <%# f.input :done, :as => :boolean %>
  <%= link_to_remove_association "Remove member", f %>
 </div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<style>

  table { 
  border: solid;
  border-radius: 5px;

  /*border-style: solid,black,rounded;*/
  color: #333;
  font-family: Helvetica, Arial, sans-serif; 
  border-collapse: 
  collapse; border-spacing: 0; 
  }

  td, th { 
  border: 1px solid transparent; /* No more visible border */
  height: 30px; 
  transition: all 0.3s;  /* Simple transition for hover effect */
  }

  th {
  background: #D11919;  /* Darken header a bit */
  font-weight: bold;
  font-size: 18px;
  }

  td {
  background: #FAFAFA;
  text-align: center;
  }
  
  thead {
    text-align: center;
  }

  /* Cells in even rows (2,4,6...) are one color */ 
  tr:nth-child(even) td { background: #F1F1F1; }   

  /* Cells in odd rows (1,3,5...) are another (excludes header cells)  */ 
  tr:nth-child(odd) td { background: #FEFEFE; }  

  tr td:hover { background: #666; color: yellow; } /* Hover cell effect! */

  .myButton {
  -moz-box-shadow: 3px 4px 0px 0px #8a2a21;
  -webkit-box-shadow: 3px 4px 0px 0px #8a2a21;
  box-shadow: 3px 4px 0px 0px #8a2a21;
  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #c62d1f), color-stop(1, #f24437));
  background:-moz-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:-webkit-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:-o-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:-ms-linear-gradient(top, #c62d1f 5%, #f24437 100%);
  background:linear-gradient(to bottom, #c62d1f 5%, #f24437 100%);
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#c62d1f', endColorstr='#f24437',GradientType=0);
  background-color:#c62d1f;
  -moz-border-radius:18px;
  -webkit-border-radius:18px;
  border-radius:18px;
  border:1px solid #d02718;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:arial;
  font-size:17px;
  padding:7px 55px;
  text-decoration:none;
  text-shadow:0px 1px 0px #810e05;
}
.myButton:hover {
  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #f24437), color-stop(1, #c62d1f));
  background:-moz-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:-webkit-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:-o-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:-ms-linear-gradient(top, #f24437 5%, #c62d1f 100%);
  background:linear-gradient(to bottom, #f24437 5%, #c62d1f 100%);
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f24437', endColorstr='#c62d1f',GradientType=0);
  background-color:#f24437;
}
.myButton:active {
  position:relative;
  top:1px;
}

#event_date {
  
    width: 140px;
    height: 140px;
    background-color: #3366FF;
    box-shadow: 10px 10px 5px #888888;

}

#event_date:hover{
outline: 5px solid black;
}

#date {

  font: 30px Tahoma, Helvetica, Arial, Sans-Serif;
  text-align: center;
  color: #222;
  text-shadow: 0px 2px 3px #555;

}
</style>

<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Domain</th>
      <th>Mentor</th>
      <% if  current_user and (current_user.category=='staff' or current_user.category=='student') %>
        <th>Approve</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= raw project.description %></td>
        <td><%= project.status.split('_').join(' ').titleize %></td>
        <td><%= project.domain %></td>
        <td><%= project.mentor.name %></td>
        <% if current_user %>
          <% if  current_user.category == 'staff' %>
            <% if project.status == 'pending' and project.mentor == current_user %>
              <td><%= link_to 'Approve',approve_path(project) %></td>
            <% elsif project.status == 'completed' %>
              <td>Approved</td>
            <% else %>
              <td>Not applied for Approval</td>
            <% end %>
          <% elsif  current_user.category == 'student' %>
            <% if project.status == 'in_progress' %>
              <td><%= link_to 'Apply for Approval',apply_path(project) %></td>
            <% else %>
              <td><%= project.status.split('_').join(' ').titleize %></td>
            <% end %>
          <% end %>
        <% end %>

          <td><%= link_to 'Show', project %></td>
        <% if current_user and (project.members.include? current_user or current_user.role == 'admin') %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } if project.members.include? current_user %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if current_user and current_user.category == 'student' %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= raw @project.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @project.domain %>
</p>

<p>
  <strong>Mentor:</strong>
  <%= @project.mentor.name %>
</p>

<%= raw @project.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
<p>
  <strong>Memebers:</strong>
  <% @project.members.each do |member| %>
    <%= member.name %>
    <br>
  <% end %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>