config/routes.rb
Rails.application.routes.draw do
  resources :statics

  resources :courses

  mount Ckeditor::Engine => '/ckeditor'
  resources :departments

  resources :news

  resources :projects

  resources :events

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'api/v1/registrations' }
  resources :users
  get '/approve/:id' ,to: 'projects#approve', as: :approve
  get '/approval/' ,to: 'projects#approval', as: :approval
  get '/apply/:id' ,to: 'projects#apply', as: :apply
  post '/save_static' ,to: 'statics#save', as: :save_static
  get 'tags/:tag', to: 'projects#index', as: :tag

  namespace :api do
  namespace :v1 do
    devise_scope :user do
      # post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end
end


end

app/models/static.rb
class Static < ActiveRecord::Base
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin!, except: [:show]

  # GET /statics
  # GET /statics.json
  def index
    @statics = Static.all
  end

  # GET /statics/1
  # GET /statics/1.json
  def show
  end

  def save
    puts params.to_json
    name = params[:contentId].split('_')[1..-2].join('_')
    puts name
    static = Static.find_by_name(name)
    if !static
      static = Static.new
      static.name=name
    end
    static.content = params[:content]
    static.save
    render :json => true
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics
  # POST /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to @static, notice: 'Static was successfully created.' }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1
  # PATCH/PUT /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to @static, notice: 'Static was successfully updated.' }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1
  # DELETE /statics/1.json
  def destroy
    @static.destroy
    respond_to do |format|
      format.html { redirect_to statics_url, notice: 'Static was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_params
      params.require(:static).permit(:name, :content)
    end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_form.html.erb
<%= simple_form_for(@static) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statics/edit.html.erb
<h1>Editing Static</h1>

<%= render 'form' %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statics.each do |static| %>
      <tr>
        <td><%= static.name %></td>
        <td><%= static.content %></td>
        <td><%= link_to 'Show', static %></td>
        <td><%= link_to 'Edit', edit_static_path(static) %></td>
        <td><%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static', new_static_path %>

app/views/statics/new.html.erb
<h1>New Static</h1>

<%= render 'form' %>

<%= link_to 'Back', statics_path %>

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @static.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @static.content %>
</p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>