config/routes.rb
Rails.application.routes.draw do
  resources :statics

  resources :courses

  mount Ckeditor::Engine => '/ckeditor'
  resources :departments

  resources :news

  resources :projects

  resources :events

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'api/v1/registrations' }
  resources :users
  get '/approve/:id' ,to: 'projects#approve', as: :approve
  get '/approval/' ,to: 'projects#approval', as: :approval
  get '/apply/:id' ,to: 'projects#apply', as: :apply
  post '/save_static' ,to: 'statics#save', as: :save_static
  get 'tags/:tag', to: 'projects#index', as: :tag

  namespace :api do
  namespace :v1 do
    devise_scope :user do
      # post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end
end


end

app/views/layouts/_messages.html.erb
<p>hello world!</p>

app/views/layouts/_navigation.html.erb
<script>
  $(document).ready(function(){
    

    /*************************Making the navbar sticky**********************************/
    
    $('#nav').affix({
      offset: {
        top: $('header').height()-$('#nav').height()
      }
    }); 

    /* highlight the top nav as scrolling occurs */
    $('body').scrollspy({ target: '#nav' })

    /* smooth scrolling for scroll to top */
    $('.scroll-top').click(function(){
      $('body,html').animate({scrollTop:0},1000);
    })

    /* smooth scrolling for nav sections */
    $('#nav .navbar-nav li>a').click(function(){
      var link = $(this).attr('href');
      var posi = $(link).offset().top+20;
      $('body,html').animate({scrollTop:posi},700);
    })

  
});
</script>




<div class="navbar navbar-custom navbar-inverse navbar-static-top" id="nav">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
      <div class = "row" style = "color:white; height:30px; font-size:20px; text-align: center;
vertical-align: middle;
line-height: 30px;">
      <span >COLLEGE OF ENGINEERING,Guindy</span>
      </div>
      <div class = "row">
        <ul class="nav navbar-nav nav-justified">
         <%= render 'layouts/navigation_links' %>
          
        </ul>
        </div>
      </div><!--/.nav-collapse -->
    </div><!--/.container -->
</div><!--/.navbar -->
       


<script type="text/javascript">
    jQuery(function ($) {
        $('#carousel1').carousel({
            interval: 2000
        });

        var clickEvent = false;

        $('#carousel1').on('click', '.nav a', function () {
            clickEvent = true;
            $('.nav li').removeClass('active');
            $(this).parent().addClass('active');
        }).on('slid.bs.carousel', function (e) {
            if (!clickEvent) {
                var count = $('.nav').children().length - 1;
                var current = $('.nav li.active');
                current.removeClass('active').next().addClass('active');
                var id = parseInt(current.data('slide-to'));
                if (count == id) {
                    $('.nav li').first().addClass('active');
                }
            }
            clickEvent = false;
        });
    });
</script>


<br><br><br><br>
<div class="contasiner">


<!-- Slider Carousel - START -->
<div class="container">
    <div id="carousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <%= image_tag '1.jpg'%>
                <div class="carousel-caption">
                    <h3>Company information</h3>
                    <p>
                        Founded in 1892 and headquartered in Fairfield, CT, General Electric Company (LSE; NYSE: GE) 
                        is a technology and financial services company. 
                        The company offers products and services ranging from aircraft engines, 
                        power generation, water processing, and household appliances, among others.
                    </p>
                </div>
            </div>
            <div class="item">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/4f77cb/ffffff&text=Social">
                <div class="carousel-caption">
                    <div class="col-lg-12 text-center v-center" style="font-size: 39pt;">
                        <a href="#"><span class="avatar"><i class="fa fa-google-plus"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-linkedin"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-facebook"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-github"></i></span></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/d11e4f/ffffff&text=Portfolio">
                <div class="carousel-caption">
                    <h3>Portfolio</h3>
                    <p>
                        This is a list of some of the work done by the company over the past quarter. 
                    </p>
                </div>
            </div>
        </div>
        
    </div>
</div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li ><%= link_to 'Home', root_path %></li>
<!-- <li><%= link_to 'About', page_path('about') %></li> -->
<li><%= link_to 'News', news_index_path %></li>
<li><%= link_to 'Projects', projects_path %></li>
<li><%= link_to 'Events', events_path %></li>
<li><%= link_to 'Departments', departments_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>
<!-- <li><a href="#">Home</a></li> -->
          <!-- <li><a href="#section2">Product</a></li>
          <li><a href="#section3">News</a></li>
          <li class="active"><a href="#section1"><strong>Big Brand</strong></a></li>
          <li><a href="#section4">About</a></li>
          <li><a href="#section5">Contact</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">SignUp/SignIn <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a data-toggle="modal" href="javascript:void(0)" onclick="openLoginModal();">Log in</a></li>
              <li><a data-toggle="modal" href="javascript:void(0)" onclick="openRegisterModal();">Register</a></div></li>
              
            </ul>
          </li> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CEGSite</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= aloha_dependencies_cdn %>
  <%= aloha_require_cdn %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="log"></div>


<!-- Wrap all page content here -->
<div id="wrap" style = "position:relative;">
  

<!--start of title page-->

 
<!--end of title page-->





  

<!-- start of navbar -->

<%= render 'layouts/navigation' %>
  
  

<!-- start of navbar -->





<div id="main">
  <% if !(params[:controller]=='visitors' and params[:action]=='index') %>
    <div class="container">
  <% else %>
    <div>
  <% end %>
      <%= yield %>
    </div>
</div>
<!--start of footer -->



<br><br><br><br><br>
<!-- <section id="footer" class="section footer" > -->
<div id = "final_footer" style = "height:100px; background-color:black; position: absolute; 
bottom: 0;margin:auto;width:100%;">
    <div class="container" style = "padding-bottom: 0px; clear:both;">
      <div class="row animated opacity mar-bot20" data-andown="fadeIn" data-animation="animation">
        <div class="col-sm-12 align-center">
                    <ul class="social-network social-circle">
                        <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
                        <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    </ul>       
        </div>
      </div>

      <!-- <div class="row align-center copyright">
          <div class="col-sm-12"><p>Copyright &copy; 2014 Amoeba - by <a href="http://bootstraptaste.com">Bootstraptaste</a></p></div>
      </div> -->
    </div>
    <br>
    <ul style = "list-style-type: none; margin: 0; padding-bottom: 0px; ">
      <li style = "display:inline"><strong>Maps and Directions&nbsp;&nbsp;|&nbsp;</strong></li>
      <li style = "display:inline"><strong>Alumni Info &nbsp;&nbsp;|&nbsp;</strong></li>
      <li style = "display:inline"><strong>Emergency Info&nbsp;&nbsp;|&nbsp;</strong></li>
    </ul>
</div>
<!-- </section> -->
<!-- <div id="footer">
  <div class="container">
    <p class="text-muted">Coded wid love by <a href="http://www.annauniv.edu">CTF</a></p>
  </div>
</div> -->
<% if !@roller.empty? %>
<div class="newsRoller">
        <div class="row">
        <div class="col-md-12 centered">
          <div id="bottom-ticker-container">
                    <ul id="bottom-ticker" class="newsTicker">
                      <% @roller.each do |news| %>
                        <li><%=  news.name %> : <%=  news.description[0..100].html_safe %><%= link_to 'Read more', news%></li>
                      <% end %>
                    </ul>
                </div>
        </div>
</div>
<% end %>
  

<!--end of footer -->



<!-- move up icon-->

<!-- <ul class="nav pull-right scroll-top">
  <li><a href="#" title="Scroll to top"><i class="glyphicon glyphicon-chevron-up"></i></a></li>
</ul> -->

<!-- move up icon-->

    <script src="http://www.alohaeditor.org/download/aloha.min.js"></script>
  </body>
</body>
</html>

app/views/layouts/slider.html.erb
<script type="text/javascript">
    jQuery(function ($) {
        $('#carousel1').carousel({
            interval: 2000
        });

        var clickEvent = false;

        $('#carousel1').on('click', '.nav a', function () {
            clickEvent = true;
            $('.nav li').removeClass('active');
            $(this).parent().addClass('active');
        }).on('slid.bs.carousel', function (e) {
            if (!clickEvent) {
                var count = $('.nav').children().length - 1;
                var current = $('.nav li.active');
                current.removeClass('active').next().addClass('active');
                var id = parseInt(current.data('slide-to'));
                if (count == id) {
                    $('.nav li').first().addClass('active');
                }
            }
            clickEvent = false;
        });
    });
</script>


<p>hello world</p>


<div class="container">

<div class="page-header">
    <h1>Slider Carousel <small>Bootstrap template, demonstrating a slider carousel with additional information</small></h1>
</div>

<!-- Slider Carousel - START -->
<div class="container">
    <div id="carousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/b4d9a7/ffffff&text=Company Information">
                <div class="carousel-caption">
                    <h3>Company information</h3>
                    <p>
                        Founded in 1892 and headquartered in Fairfield, CT, General Electric Company (LSE; NYSE: GE) 
                        is a technology and financial services company. 
                        The company offers products and services ranging from aircraft engines, 
                        power generation, water processing, and household appliances, among others.
                    </p>
                </div>
            </div>
            <div class="item">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/4f77cb/ffffff&text=Social">
                <div class="carousel-caption">
                    <div class="col-lg-12 text-center v-center" style="font-size: 39pt;">
                        <a href="#"><span class="avatar"><i class="fa fa-google-plus"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-linkedin"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-facebook"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-github"></i></span></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/d11e4f/ffffff&text=Portfolio">
                <div class="carousel-caption">
                    <h3>Portfolio</h3>
                    <p>
                        This is a list of some of the work done by the company over the past quarter. 
                    </p>
                </div>
            </div>
        </div>
        
    </div>
</div>